import type { CalendarItem } from "@/lib/types"

// Generate calendar items spread across February 2026
export const mockCalendarItems: CalendarItem[] = [
  // Feb 3
  {
    id: "cal-1",
    date: new Date(2026, 1, 3),
    type: "inflow",
    category: "expected",
    entityName: "Acme Corp",
    entityId: "cust_001",
    reference: "INV-2026-0865",
    amount: 24500,
    confidence: 96,
    isDraggable: false,
  },
  // Feb 4
  {
    id: "cal-2",
    date: new Date(2026, 1, 4),
    type: "outflow",
    category: "scheduled",
    entityName: "Raw Materials Co",
    entityId: "vend_001",
    reference: "BILL-2026-0234",
    amount: 18200,
    isDraggable: true,
    originalDueDate: new Date(2026, 1, 10),
    paymentMethod: "ACH",
  },
  // Feb 5
  {
    id: "cal-3",
    date: new Date(2026, 1, 5),
    type: "inflow",
    category: "expected",
    entityName: "Bright Solutions",
    entityId: "cust_002",
    reference: "INV-2026-0871",
    amount: 15800,
    confidence: 88,
    isDraggable: false,
  },
  {
    id: "cal-4",
    date: new Date(2026, 1, 5),
    type: "outflow",
    category: "due",
    entityName: "City Utilities",
    entityId: "vend_002",
    reference: "BILL-2026-0240",
    amount: 3450,
    isDraggable: false,
    paymentMethod: "ACH",
  },
  // Feb 7
  {
    id: "cal-5",
    date: new Date(2026, 1, 7),
    type: "outflow",
    category: "scheduled",
    entityName: "Logistics Plus",
    entityId: "vend_003",
    reference: "BILL-2026-0251",
    amount: 12600,
    isDraggable: true,
    originalDueDate: new Date(2026, 1, 14),
    paymentMethod: "ACH",
  },
  // Feb 9 (today)
  {
    id: "cal-6",
    date: new Date(2026, 1, 9),
    type: "inflow",
    category: "expected",
    entityName: "Metro Retail Group",
    entityId: "cust_003",
    reference: "INV-2026-0880",
    amount: 67800,
    confidence: 94,
    isDraggable: false,
  },
  {
    id: "cal-7",
    date: new Date(2026, 1, 9),
    type: "outflow",
    category: "due",
    entityName: "Insurance Premium",
    entityId: "vend_004",
    reference: "BILL-2026-0260",
    amount: 4200,
    isDraggable: false,
    paymentMethod: "ACH",
  },
  // Feb 10
  {
    id: "cal-8",
    date: new Date(2026, 1, 10),
    type: "outflow",
    category: "scheduled",
    entityName: "Equipment Supplier",
    entityId: "vend_005",
    reference: "BILL-2026-0265",
    amount: 45000,
    isDraggable: true,
    originalDueDate: new Date(2026, 1, 15),
    paymentMethod: "Wire",
  },
  // Feb 12
  {
    id: "cal-9",
    date: new Date(2026, 1, 12),
    type: "inflow",
    category: "expected",
    entityName: "Summit Enterprises",
    entityId: "cust_004",
    reference: "INV-2026-0890",
    amount: 31200,
    confidence: 82,
    isDraggable: false,
  },
  {
    id: "cal-10",
    date: new Date(2026, 1, 12),
    type: "outflow",
    category: "due",
    entityName: "Kiln Services",
    entityId: "vend_006",
    reference: "BILL-2026-0270",
    amount: 8400,
    isDraggable: false,
    paymentMethod: "ACH",
  },
  // Feb 14
  {
    id: "cal-11",
    date: new Date(2026, 1, 14),
    type: "inflow",
    category: "expected",
    entityName: "Pacific Trading",
    entityId: "cust_005",
    reference: "INV-2026-0895",
    amount: 19400,
    confidence: 72,
    isDraggable: false,
  },
  // Feb 16
  {
    id: "cal-12",
    date: new Date(2026, 1, 16),
    type: "outflow",
    category: "scheduled",
    entityName: "Office Rent",
    entityId: "vend_007",
    reference: "BILL-2026-0280",
    amount: 8500,
    isDraggable: true,
    originalDueDate: new Date(2026, 1, 20),
    paymentMethod: "ACH",
  },
  // Feb 18
  {
    id: "cal-13",
    date: new Date(2026, 1, 18),
    type: "inflow",
    category: "expected",
    entityName: "North Star Industries",
    entityId: "cust_006",
    reference: "INV-2026-0902",
    amount: 42300,
    confidence: 90,
    isDraggable: false,
  },
  {
    id: "cal-14",
    date: new Date(2026, 1, 18),
    type: "outflow",
    category: "due",
    entityName: "Clay Supply Co",
    entityId: "vend_008",
    reference: "BILL-2026-0285",
    amount: 22100,
    isDraggable: false,
    paymentMethod: "Check",
  },
  // Feb 20
  {
    id: "cal-15",
    date: new Date(2026, 1, 20),
    type: "inflow",
    category: "expected",
    entityName: "Greenfield Partners",
    entityId: "cust_007",
    reference: "INV-2026-0910",
    amount: 28900,
    confidence: 85,
    isDraggable: false,
  },
  // Feb 21
  {
    id: "cal-16",
    date: new Date(2026, 1, 21),
    type: "outflow",
    category: "scheduled",
    entityName: "Marketing Agency",
    entityId: "vend_009",
    reference: "BILL-2026-0290",
    amount: 6200,
    isDraggable: true,
    originalDueDate: new Date(2026, 1, 25),
    paymentMethod: "Card",
  },
  // Feb 23
  {
    id: "cal-17",
    date: new Date(2026, 1, 23),
    type: "inflow",
    category: "expected",
    entityName: "Delta Corp",
    entityId: "cust_008",
    reference: "INV-2026-0918",
    amount: 55600,
    confidence: 78,
    isDraggable: false,
  },
  // Feb 24
  {
    id: "cal-18",
    date: new Date(2026, 1, 24),
    type: "outflow",
    category: "due",
    entityName: "Payroll",
    entityId: "vend_010",
    reference: "PAY-2026-FEB2",
    amount: 86400,
    isDraggable: false,
    paymentMethod: "ACH",
  },
  // Feb 25
  {
    id: "cal-19",
    date: new Date(2026, 1, 25),
    type: "outflow",
    category: "scheduled",
    entityName: "Cloud Hosting",
    entityId: "vend_011",
    reference: "BILL-2026-0300",
    amount: 3800,
    isDraggable: true,
    originalDueDate: new Date(2026, 1, 28),
    paymentMethod: "Card",
  },
  // Feb 26
  {
    id: "cal-20",
    date: new Date(2026, 1, 26),
    type: "inflow",
    category: "expected",
    entityName: "Westside Distribution",
    entityId: "cust_009",
    reference: "INV-2026-0925",
    amount: 37500,
    confidence: 91,
    isDraggable: false,
  },
  // Feb 27
  {
    id: "cal-21",
    date: new Date(2026, 1, 27),
    type: "outflow",
    category: "scheduled",
    entityName: "New Vendor LLC",
    entityId: "vend_012",
    reference: "BILL-2026-0305",
    amount: 8200,
    isDraggable: true,
    originalDueDate: new Date(2026, 2, 3),
    paymentMethod: "ACH",
  },
  // Feb 28
  {
    id: "cal-22",
    date: new Date(2026, 1, 28),
    type: "inflow",
    category: "expected",
    entityName: "TechForward Inc",
    entityId: "cust_010",
    reference: "INV-2026-0930",
    amount: 21200,
    confidence: 68,
    isDraggable: false,
  },
]
