import type { ExecutionItem } from "@/lib/types"

export const mockExecutionItems: ExecutionItem[] = [
  // Executing
  {
    id: "exec-1",
    type: "payment",
    status: "executing",
    entityName: "Raw Materials Co",
    entityId: "vend_001",
    reference: "INV-2026-0234",
    terms: "Net 30",
    amount: 18200,
    scheduledDate: new Date(2026, 1, 9),
    scheduledTime: "9:00 AM",
    method: "ACH",
    accountLastFour: "4521",
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-08T14:00:00"), action: "Scheduled", userId: "sys", userName: "System", details: "Auto-scheduled from cash plan" },
      { timestamp: new Date("2026-02-09T09:00:00"), action: "Execution started", userId: "sys", userName: "System" },
    ],
  },
  {
    id: "exec-2",
    type: "payment",
    status: "executing",
    entityName: "Kiln Services",
    entityId: "vend_006",
    reference: "INV-2026-0270",
    terms: "Net 15",
    amount: 8400,
    scheduledDate: new Date(2026, 1, 9),
    scheduledTime: "9:00 AM",
    method: "ACH",
    accountLastFour: "4521",
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-07T10:00:00"), action: "Scheduled", userId: "u1", userName: "Sarah Chen" },
      { timestamp: new Date("2026-02-09T09:00:00"), action: "Execution started", userId: "sys", userName: "System" },
    ],
  },
  // Pending Approval
  {
    id: "exec-3",
    type: "payment",
    status: "pending_approval",
    entityName: "Equipment Supplier Inc",
    entityId: "vend_005",
    reference: "INV-2026-0265",
    terms: "Net 30",
    amount: 45000,
    scheduledDate: new Date(2026, 1, 10),
    scheduledTime: "6:00 AM",
    method: "Wire",
    accountLastFour: "7832",
    requiresApproval: true,
    approvers: [
      { userId: "u1", name: "Sarah Chen", status: "approved", timestamp: new Date("2026-02-08T16:00:00") },
      { userId: "u2", name: "Michael Torres", status: "pending" },
    ],
    auditLog: [
      { timestamp: new Date("2026-02-07T08:00:00"), action: "Scheduled", userId: "sys", userName: "System" },
      { timestamp: new Date("2026-02-08T16:00:00"), action: "Approved by Sarah Chen", userId: "u1", userName: "Sarah Chen" },
    ],
  },
  {
    id: "exec-4",
    type: "payment",
    status: "pending_approval",
    entityName: "New Vendor LLC",
    entityId: "vend_012",
    reference: "INV-2026-0305",
    terms: "Net 30",
    amount: 8200,
    scheduledDate: new Date(2026, 1, 27),
    scheduledTime: "6:00 AM",
    method: "ACH",
    accountLastFour: "4521",
    requiresApproval: true,
    approvers: [{ userId: "u2", name: "Michael Torres", status: "pending" }],
    auditLog: [
      { timestamp: new Date("2026-02-08T12:00:00"), action: "Scheduled", userId: "sys", userName: "System", details: "First payment to new vendor - requires manual approval" },
    ],
  },
  {
    id: "exec-5",
    type: "payment",
    status: "pending_approval",
    entityName: "Premium Logistics",
    entityId: "vend_013",
    reference: "INV-2026-0310",
    terms: "Net 15",
    amount: 32500,
    scheduledDate: new Date(2026, 1, 15),
    scheduledTime: "6:00 AM",
    method: "Wire",
    accountLastFour: "7832",
    requiresApproval: true,
    approvers: [{ userId: "u2", name: "Michael Torres", status: "pending" }],
    auditLog: [
      { timestamp: new Date("2026-02-08T14:00:00"), action: "Scheduled", userId: "sys", userName: "System", details: "Exceeds $25K auto-approval threshold" },
    ],
  },
  // Scheduled
  {
    id: "exec-6",
    type: "payment",
    status: "scheduled",
    entityName: "Logistics Plus",
    entityId: "vend_003",
    reference: "INV-2026-0251",
    terms: "Net 30",
    amount: 12600,
    scheduledDate: new Date(2026, 1, 10),
    scheduledTime: "6:00 AM",
    method: "ACH",
    accountLastFour: "4521",
    autoExecuteCountdown: "14h 23m",
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-06T09:00:00"), action: "Scheduled", userId: "sys", userName: "System", details: "Auto-scheduled to optimize cash flow" },
    ],
  },
  {
    id: "exec-7",
    type: "payment",
    status: "scheduled",
    entityName: "City Utilities",
    entityId: "vend_002",
    reference: "BILL-2026-0240",
    terms: "Due on receipt",
    amount: 3450,
    scheduledDate: new Date(2026, 1, 10),
    scheduledTime: "8:00 AM",
    method: "ACH",
    accountLastFour: "4521",
    autoExecuteCountdown: "16h 23m",
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-05T10:00:00"), action: "Scheduled", userId: "u1", userName: "Sarah Chen" },
    ],
  },
  {
    id: "exec-8",
    type: "payment",
    status: "scheduled",
    entityName: "Insurance Premium",
    entityId: "vend_004",
    reference: "BILL-2026-0260",
    terms: "Monthly",
    amount: 4200,
    scheduledDate: new Date(2026, 1, 11),
    scheduledTime: "6:00 AM",
    method: "ACH",
    accountLastFour: "4521",
    autoExecuteCountdown: "1d 14h",
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-01T08:00:00"), action: "Scheduled", userId: "sys", userName: "System", details: "Recurring monthly payment" },
    ],
  },
  {
    id: "exec-9",
    type: "payment",
    status: "scheduled",
    entityName: "Office Rent",
    entityId: "vend_007",
    reference: "BILL-2026-0280",
    terms: "Monthly",
    amount: 8500,
    scheduledDate: new Date(2026, 1, 16),
    scheduledTime: "6:00 AM",
    method: "ACH",
    accountLastFour: "4521",
    autoExecuteCountdown: "6d 14h",
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-01T08:00:00"), action: "Scheduled", userId: "sys", userName: "System", details: "Recurring monthly payment" },
    ],
  },
  {
    id: "exec-10",
    type: "payment",
    status: "scheduled",
    entityName: "Clay Supply Co",
    entityId: "vend_008",
    reference: "BILL-2026-0285",
    terms: "Net 30",
    amount: 22100,
    scheduledDate: new Date(2026, 1, 18),
    scheduledTime: "6:00 AM",
    method: "Check",
    accountLastFour: "4521",
    autoExecuteCountdown: "8d 14h",
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-08T09:00:00"), action: "Scheduled", userId: "sys", userName: "System" },
    ],
  },
  {
    id: "exec-11",
    type: "payment",
    status: "scheduled",
    entityName: "Marketing Agency",
    entityId: "vend_009",
    reference: "BILL-2026-0290",
    terms: "Net 15",
    amount: 6200,
    scheduledDate: new Date(2026, 1, 21),
    scheduledTime: "6:00 AM",
    method: "Card",
    accountLastFour: "9104",
    autoExecuteCountdown: "11d 14h",
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-08T11:00:00"), action: "Scheduled", userId: "sys", userName: "System" },
    ],
  },
  {
    id: "exec-12",
    type: "payment",
    status: "scheduled",
    entityName: "Payroll",
    entityId: "vend_010",
    reference: "PAY-2026-FEB2",
    terms: "Bi-weekly",
    amount: 86400,
    scheduledDate: new Date(2026, 1, 24),
    scheduledTime: "6:00 AM",
    method: "ACH",
    accountLastFour: "4521",
    autoExecuteCountdown: "14d 14h",
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-01T08:00:00"), action: "Scheduled", userId: "sys", userName: "System", details: "Recurring bi-weekly payroll" },
    ],
  },
  {
    id: "exec-13",
    type: "payment",
    status: "scheduled",
    entityName: "Cloud Hosting",
    entityId: "vend_011",
    reference: "BILL-2026-0300",
    terms: "Monthly",
    amount: 3800,
    scheduledDate: new Date(2026, 1, 25),
    scheduledTime: "8:00 AM",
    method: "Card",
    accountLastFour: "9104",
    autoExecuteCountdown: "15d 16h",
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-01T08:00:00"), action: "Scheduled", userId: "sys", userName: "System", details: "Recurring monthly subscription" },
    ],
  },
  // Completed
  {
    id: "exec-14",
    type: "payment",
    status: "completed",
    entityName: "Packaging Materials Inc",
    entityId: "vend_014",
    reference: "INV-2026-0200",
    terms: "Net 30",
    amount: 9800,
    scheduledDate: new Date(2026, 1, 7),
    scheduledTime: "6:00 AM",
    method: "ACH",
    accountLastFour: "4521",
    executedAt: new Date("2026-02-07T06:02:00"),
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-05T14:00:00"), action: "Scheduled", userId: "sys", userName: "System" },
      { timestamp: new Date("2026-02-07T06:00:00"), action: "Execution started", userId: "sys", userName: "System" },
      { timestamp: new Date("2026-02-07T06:02:00"), action: "Completed", userId: "sys", userName: "System" },
    ],
  },
  {
    id: "exec-15",
    type: "payment",
    status: "completed",
    entityName: "Glaze Supplier Ltd",
    entityId: "vend_015",
    reference: "INV-2026-0210",
    terms: "Net 15",
    amount: 14300,
    scheduledDate: new Date(2026, 1, 6),
    scheduledTime: "6:00 AM",
    method: "ACH",
    accountLastFour: "4521",
    executedAt: new Date("2026-02-06T06:01:00"),
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-04T09:00:00"), action: "Scheduled", userId: "u1", userName: "Sarah Chen" },
      { timestamp: new Date("2026-02-06T06:00:00"), action: "Execution started", userId: "sys", userName: "System" },
      { timestamp: new Date("2026-02-06T06:01:00"), action: "Completed", userId: "sys", userName: "System" },
    ],
  },
  {
    id: "exec-16",
    type: "payment",
    status: "completed",
    entityName: "Shipping Partners Co",
    entityId: "vend_016",
    reference: "INV-2026-0215",
    terms: "Net 30",
    amount: 7600,
    scheduledDate: new Date(2026, 1, 5),
    scheduledTime: "6:00 AM",
    method: "ACH",
    accountLastFour: "4521",
    executedAt: new Date("2026-02-05T06:03:00"),
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-03T10:00:00"), action: "Scheduled", userId: "sys", userName: "System" },
      { timestamp: new Date("2026-02-05T06:00:00"), action: "Execution started", userId: "sys", userName: "System" },
      { timestamp: new Date("2026-02-05T06:03:00"), action: "Completed", userId: "sys", userName: "System" },
    ],
  },
  {
    id: "exec-17",
    type: "collection",
    status: "completed",
    entityName: "Acme Corp",
    entityId: "cust_001",
    reference: "INV-2026-0850",
    terms: "Net 30",
    amount: 18900,
    scheduledDate: new Date(2026, 1, 3),
    scheduledTime: "N/A",
    method: "ACH",
    accountLastFour: "4521",
    executedAt: new Date("2026-02-03T14:30:00"),
    requiresApproval: false,
    auditLog: [
      { timestamp: new Date("2026-02-03T14:30:00"), action: "Payment received", userId: "sys", userName: "System", details: "ACH deposit confirmed" },
    ],
  },
]
